/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesCateringRouteImport } from './routes/services.catering'
import { Route as ServicesHospitalityRouteImport } from './routes/services.hospitality'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCateringRoute = ServicesCateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesHospitalityRoute = ServicesHospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/catering': typeof CateringRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hospitality': typeof HospitalityRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/catering': typeof ServicesCateringRoute
  '/services/hospitality': typeof ServicesHospitalityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/catering': typeof CateringRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hospitality': typeof HospitalityRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/catering': typeof ServicesCateringRoute
  '/services/hospitality': typeof ServicesHospitalityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/catering': typeof CateringRoute
  '/certificates': typeof CertificatesRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/hospitality': typeof HospitalityRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/catering': typeof ServicesCateringRoute
  '/services/hospitality': typeof ServicesHospitalityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career'
    | '/catering'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/gallery'
    | '/hospitality'
    | '/services'
    | '/services/catering'
    | '/services/hospitality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/catering'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/gallery'
    | '/hospitality'
    | '/services'
    | '/services/catering'
    | '/services/hospitality'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career'
    | '/catering'
    | '/certificates'
    | '/clients'
    | '/contact'
    | '/gallery'
    | '/hospitality'
    | '/services'
    | '/services/catering'
    | '/services/hospitality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRoute
  CateringRoute: typeof CateringRoute
  CertificatesRoute: typeof CertificatesRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HospitalityRoute: typeof HospitalityRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/catering': {
      id: '/services/catering'
      path: '/catering'
      fullPath: '/services/catering'
      preLoaderRoute: typeof ServicesCateringRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/hospitality': {
      id: '/services/hospitality'
      path: '/hospitality'
      fullPath: '/services/hospitality'
      preLoaderRoute: typeof ServicesHospitalityRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCateringRoute: typeof ServicesCateringRoute
  ServicesHospitalityRoute: typeof ServicesHospitalityRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCateringRoute: ServicesCateringRoute,
  ServicesHospitalityRoute: ServicesHospitalityRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRoute,
  CateringRoute: CateringRoute,
  CertificatesRoute: CertificatesRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HospitalityRoute: HospitalityRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
